// Mocks generated by Mockito 5.4.6 from annotations
// in flower_app/test/features/auth/signUp/domain/repositories/signup_repo_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flower_app/core/models/api_result.dart' as _i4;
import 'package:flower_app/features/auth/signUp/domain/entities/signup_request_entity.dart'
    as _i6;
import 'package:flower_app/features/auth/signUp/domain/entities/signup_response_entity.dart'
    as _i5;
import 'package:flower_app/features/auth/signUp/domain/repositories/signup_repo.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SignupRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignupRepo extends _i1.Mock implements _i2.SignupRepo {
  MockSignupRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<_i5.SignupResponseEntity>> signup(
    _i6.SignupRequestEntity? signup,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signup, [signup]),
            returnValue:
                _i3.Future<_i4.ApiResult<_i5.SignupResponseEntity>>.value(
                  _i7.dummyValue<_i4.ApiResult<_i5.SignupResponseEntity>>(
                    this,
                    Invocation.method(#signup, [signup]),
                  ),
                ),
          )
          as _i3.Future<_i4.ApiResult<_i5.SignupResponseEntity>>);
}
