name: flower_app
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  flutter_screenutil: ^5.9.3
  flutter_bloc: ^9.1.0
  flutter_svg: ^2.1.0
  flutter_native_splash: ^2.4.6
  dio: ^5.8.0+1
  auto_size_text: ^3.0.0
  connectivity_plus: ^6.1.3
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.3
  dartz: ^0.10.1
  animated_custom_dropdown: ^3.1.1
  get_it: ^8.0.3
  mockito: ^5.4.5
  injectable: ^2.5.0
  equatable: ^2.0.7
  flutter_secure_storage: ^9.2.4
  flutter_localizations:
    sdk: flutter
  intl: any
  dots_indicator: ^4.0.1
  google_maps_flutter: ^2.12.1
  geolocator: ^14.0.0
  geocoding: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  injectable_generator: ^2.7.0


  flutter_lints: ^5.0.0
  json_serializable: ^6.9.5


flutter:


  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/data/about_us.json
    - assets/data/terms_conditions.json
    - assets/files/
