name: Test Firebase Authentication

on:
  push:
    branches:
      - master

jobs:
  distribute:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload app to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: 1:293463341935:android:d00b98b794357778d0069a
          serviceCredentialsFile: firebase-service-account.json
          groups: testers
          file: build/app/outputs/flutter-apk/app-release.apk