name: Distribute to Firebase

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Firebase CLI
        run: npm install -g firebase-tools@13.0.0

      - name: Test Firebase Login
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/firebase-service-account.json
        run: |
          # Show current directory contents
          echo "Listing repo root:"
          ls -la
          
          # Verify service account exists
          if [ ! -f "$GOOGLE_APPLICATION_CREDENTIALS" ]; then
            echo "Error: Service account file not found at $GOOGLE_APPLICATION_CREDENTIALS"
            exit 1
          fi
          
          # Set proper permissions on the service account file
          chmod 600 "$GOOGLE_APPLICATION_CREDENTIALS"
          
          # Test Firebase CLI version
          firebase --version
          
          # Test Firebase authentication with detailed error output
          echo "Testing Firebase authentication..."
          firebase projects:list || { echo "Authentication failed"; cat ~/.firebase-debug.log; exit 1; }
          
          echo "Authentication successful!"
        shell: bash