name: Distribute to Firebase

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Copy service account key and authenticate
        run: |
          cp firebase-service-account.json $HOME/firebase-key.json
          export GOOGLE_APPLICATION_CREDENTIALS="$HOME/firebase-key.json"
          firebase projects:list
        shell: bash

      - name: Upload to Firebase App Distribution
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS="$HOME/firebase-key.json"
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
            --app "1:1234567890:android:abcdef1234567890" \
            --groups "testers"
        shell: bash
