name: Distribute to Firebase

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate and Upload to Firebase App Distribution
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/firebase-key.json
        run: |
          # Show current directory contents
          echo "Listing repo root:"
          ls -la

          # Copy service account key to home
          cp firebase-service-account.json $HOME/firebase-key.json

          # Confirm the key was copied
          echo "Listing home directory:"
          ls -la $HOME/firebase-key.json

          # Test Firebase authentication
          firebase projects:list

          # Upload the APK to Firebase App Distribution
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
            --app "1:293463341935:android:d00b98b794357778d0069a" \
            --groups "testers"
        shell: bash
