name: Distribute to Firebase

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

#      - name: Set up Flutter
#        uses: subosito/flutter-action@v2
#        with:
#          flutter-version: '3.29.3'
#
#      - name: Install dependencies
#        run: flutter pub get
#
#      - name: Build APK
#        run: flutter build apk --release

      - name: Install Firebase CLI
        run: npm install -g firebase-tools@13.0.0

      - name: Authenticate and Upload to Firebase App Distribution
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/firebase-key.json
        run: |
          # Show current directory contents
          echo "Listing repo root:"
          ls -la

          # Copy service account key to home
          cp firebase-service-account.json $HOME/firebase-key.json

          # Set permissions on the key
          chmod 600 $HOME/firebase-key.json

          # Confirm the key was copied
          echo "Listing home directory:"
          ls -la $HOME/firebase-key.json

          # Verify key content (for debugging, shows first few characters)
          head -n 2 $HOME/firebase-key.json

          # Verify APK exists
          echo "Listing APK directory:"
          ls -la build/app/outputs/flutter-apk/

          # Test Firebase CLI
          firebase --version

          # Test Firebase authentication with detailed error output
          echo "Testing Firebase authentication..."
          firebase projects:list --service-account $HOME/firebase-key.json || { echo "Authentication failed"; exit 1; }

          # Upload the APK to Firebase App Distribution
          echo "Uploading APK to Firebase App Distribution..."
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
            --app "1:293463341935:android:d00b98b794357778d0069a" \
            --groups "testers" \
            --service-account $HOME/firebase-key.json
        shell: bash